{"name": "User enters username and incorrect password", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\ruche\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\ruche\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\step_definition.py\", line 49, in step_impl\n    assert error_message == \"Invalid password\"\n"}, "steps": [{"name": "Given User is on the login page", "status": "passed", "start": 1621782782224, "stop": 1621782782238}, {"name": "When User enters the username", "status": "passed", "start": 1621782782239, "stop": 1621782782589}, {"name": "And User enters the \"password\"", "status": "passed", "start": 1621782782589, "stop": 1621782783341}, {"name": "Then Error should be displayed", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\ruche\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\ruche\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\step_definition.py\", line 49, in step_impl\n    assert error_message == \"Invalid password\"\n"}, "start": 1621782783342, "stop": 1621782783456}], "start": 1621782772482, "stop": 1621782785699, "uuid": "ddbbfbc7-d98a-4758-9caf-61475f25bd0f", "historyId": "a14bd5d5264d82a0264182d809d1e673", "fullName": "User should be able to login: User enters username and incorrect password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User should be able to login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}